---
- name: Configure Azure App Service
  hosts: localhost
  connection: local
  vars:
    resource_group_name: "{{ resource_group_name | default(omit) }}"
    app_service_name: "{{ app_service_name | default(omit) }}"
  tasks:
    
    
    - name: Set App Settings (key-value pairs)
      azure.azcollection.azure_rm_webapp:
        resource_group: "{{ resource_group_name }}"
        name: "{{ app_service_name }}"
        app_settings:
          MY_KEY_1: "my_value_1"
          MY_KEY_2: "my_value_2"
      register: app_settings_result

    - name: Output App Settings result
      debug:
        var: app_settings_result

    - name: Configure Logging and Monitoring
      azure.azcollection.azure_rm_webapp:
        resource_group: "{{ resource_group_name }}"
        name: "{{ app_service_name }}"
        logs:
          application_logs:
            file_system_level: 'Information'
          http_logs:
            file_system:
              retention_in_mb: 35
              retention_in_days: 7
              enabled: true
          detailed_error_messages: true
          failed_request_tracing: true
      register: logging_monitoring_result

    - name: Output Logging and Monitoring result
      debug:
        var: logging_monitoring_result

    - name: Add Common Tags
      azure.azcollection.azure_rm_webapp:
        resource_group: "{{ resource_group_name }}"
        name: "{{ app_service_name }}"
        tags:
          environment: "production"
          owner: "devops-team"
          project: "sample-app"
      register: tags_result

    - name: Output Tags result
      debug:
        var: tags_result
