name: Setup Ansible with Azure Collection

on:
  workflow_dispatch:  # Trigger manually via GitHub UI

jobs:
  setup-ansible:
    runs-on: ubuntu-latest
    env:
      RESOURCE_GROUP_NAME: 'tf-app-rg'  # Replace with your resource group name
      APP_SERVICE_NAME: 'tf-basic-app'  # Replace with your App Service name
      

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Ansible and Azure Collection
        run: |
          python -m pip install --upgrade pip
          pip install ansible
          ansible-galaxy collection list azure.azcollection
          ansible-galaxy collection install azure.azcollection:3.3.1
          ansible-galaxy collection list azure.azcollection
      
      - name: Install Ansible Azure Dependencies
        working-directory: ./ansible
        run: |
          pip3 install -r ~/.ansible/collections/ansible_collections/azure/azcollection/requirements.txt
          pip list | grep azure
      - name: Display Tools versions
        run: |
          echo "Python version: $(python --version)"
          echo "Python3 version: $(python3 --version)"
          echo "pip version: $(pip --version)"
          echo "pip3 version: $(pip3 --version)"
          echo "Ansible version: $(ansible --version)"
          echo "Azure CLI version: $(az --version)"
          echo "GitHub Actions runner OS: $(uname -a)"
          echo "GitHub Actions runner architecture: $(uname -m)"
          
      - name: Verify Installation
        run: |
          ansible --version
          ansible-galaxy collection list | grep azure.azcollection
      
      - name: Run Ansible Playbook
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_SECRET: ${{ secrets.AZURE_SECRET }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_TENANT: ${{ secrets.AZURE_TENANT_ID }}
        run: |
          ansible-playbook -i localhost, ./ansible/configure_app_service.yml --extra-vars "resource_group_name=$RESOURCE_GROUP_NAME app_service_name=$APP_SERVICE_NAME"
